
# word_bank.py

word_bank = {
    1: {
        # 100 words for Grade 1 - very simple, common nouns/verbs/adjectives
        "cat": "a small pet animal",
        "dog": "a common pet animal that barks",
        "ball": "a round object used in games",
        "hat": "a piece of clothing worn on the head",
        "book": "a set of written or printed pages",
        "bat": "used to hit a ball in sports",
        "pen": "a tool for writing with ink",
        "cup": "a small container for drinking",
        "sun": "the star that gives light to Earth",
        "moon": "a round object that orbits the Earth",
        "bed": "a piece of furniture for sleeping",
        "car": "a vehicle with four wheels",
        "bus": "a large vehicle that carries people",
        "egg": "a round object from a bird",
        "toy": "something children play with",
        "fish": "an animal that lives in water",
        "cow": "a farm animal that gives milk",
        "pig": "a farm animal with a flat nose",
        "run": "to move quickly on foot",
        "sit": "to rest on a chair",
        "fan": "a machine that moves air",
        "map": "a drawing of land or area",
        "box": "a container for things",
        "cup": "used for drinking",
        "top": "the highest point",
        "leg": "part of the body for walking",
        "arm": "part of the body used for lifting",
        "ear": "organ for hearing",
        "eye": "organ for seeing",
        "red": "a color",
        "big": "large in size",
        "hot": "having a high temperature",
        "cold": "having a low temperature",
        "wet": "covered in water",
        "dry": "not wet",
        "bag": "something used to carry things",
        "box": "square container",
        "cup": "small container for drinking",
        "jam": "sweet food made from fruit",
        "pan": "used for cooking",
        "man": "an adult male",
        "boy": "a young male child",
        "girl": "a young female child",
        "hen": "a bird that lays eggs",
        "rat": "a small animal",
        "bat": "flying animal at night",
        "zip": "fastener on clothes",
        "lip": "part of the mouth",
        "tip": "the end of something",
        "ink": "colored liquid for writing",
        "sky": "the space above us",
        "star": "a bright light in the night sky",
        "key": "used to open locks",
        "box": "used to store things",
        "cap": "a soft hat",
        "pet": "an animal kept at home",
        "jam": "sweet spread for bread",
        "bus": "large vehicle for passengers",
        "toy": "something children play with",
        "mat": "used to wipe feet",
        "pen": "used for writing",
        "net": "mesh used to catch fish",
        "web": "spider’s home",
        "bee": "an insect that makes honey",
        "ant": "a small insect",
        "fox": "a wild animal",
        "cup": "drinking container",
        "zip": "fastener",
        "van": "a vehicle",
        "sun": "gives light",
        "win": "to succeed",
        "run": "to move fast",
        "ten": "a number",
        "six": "a number",
        "one": "a number",
        "two": "a number",
        "cow": "farm animal",
        "pig": "farm animal",
        "hen": "farm bird",
        "egg": "bird product",
        "bus": "passenger vehicle",
        "car": "vehicle",
        "dog": "pet animal",
        "cat": "pet animal",
        "bat": "sports tool",
        "bag": "carries things",
        "cup": "drinking container",
        "toy": "plaything",
        "fan": "machine for air",
        "red": "a color",
        "top": "highest part",
        "box": "container",
        "key": "opens locks",
        "jam": "fruit spread",
    },

    2: {
        # 100 words for Grade 2 - slightly harder, objects, nature, daily use
        "apple": "a round fruit with red or green skin",
        "school": "a place where children learn",
        "house": "a building where people live",
        "water": "a clear liquid we drink",
        "table": "furniture with a flat top",
        "chair": "something used to sit on",
        "tree": "a tall plant with a trunk",
        "river": "a large stream of water",
        "stone": "a small hard rock",
        "bird": "an animal with feathers and wings",
        "milk": "a white drink from cows",
        "bread": "a food made from flour",
        "plate": "a flat dish for eating",
        "glass": "used for drinking water",
        "shirt": "clothing for the upper body",
        "pants": "clothing for legs",
        "shoes": "footwear",
        "clock": "shows the time",
        "door": "used to enter a room",
        "window": "glass opening in a wall",
        "floor": "the bottom of a room",
        "roof": "the top of a house",
        "wall": "part of a building",
        "road": "path for cars",
        "park": "a place for playing and walking",
        "train": "a vehicle on tracks",
        "boat": "a vehicle on water",
        "farm": "a place where crops and animals grow",
        "milk": "drink from cows",
        "corn": "a yellow food grown in fields",
        "salt": "white seasoning",
        "sugar": "sweet seasoning",
        "knife": "tool for cutting",
        "spoon": "used for eating",
        "fork": "used for eating",
        "lamp": "gives light",
        "light": "brightness",
        "dark": "without light",
        "day": "time with sunlight",
        "night": "time of darkness",
        "book": "pages with writing",
        "story": "tale of events",
        "paper": "thin sheet for writing",
        "pencil": "tool for writing",
        "eraser": "used to remove pencil",
        "bag": "used to carry things",
        "ball": "round toy",
        "bell": "makes ringing sound",
        "song": "words with music",
        "dance": "move with rhythm",
        "game": "activity for fun",
        "play": "to have fun",
        "jump": "to move off the ground",
        "walk": "to move on feet",
        "stand": "to be upright",
        "sit": "to rest on a chair",
        "read": "to look at words",
        "write": "to make words",
        "draw": "to make pictures",
        "paint": "to color pictures",
        "color": "red, blue, yellow, etc.",
        "blue": "a color",
        "green": "a color",
        "black": "a color",
        "white": "a color",
        "orange": "a fruit and color",
        "grape": "a small fruit",
        "mango": "a yellow fruit",
        "banana": "a yellow fruit",
        "pear": "a green fruit",
        "peach": "a soft fruit",
        "rice": "grain food",
        "meat": "food from animals",
        "egg": "food from birds",
        "cake": "sweet baked food",
        "juice": "drink from fruit",
        "rain": "water falling from sky",
        "snow": "frozen water from sky",
        "wind": "moving air",
        "sky": "above us",
        "cloud": "white thing in sky",
        "star": "bright in night",
        "sun": "gives light",
        "moon": "seen at night",
        "toy": "plaything",
        "car": "vehicle",
        "bus": "vehicle",
        "truck": "large vehicle",
        "bike": "two-wheeled vehicle",
        "shop": "place to buy things",
        "coin": "metal money",
        "note": "paper money",
        "bag": "something to carry items",
        "box": "container",
        "gift": "something given",
        "ring": "worn on finger",
        "watch": "shows time",
    },

    3: {
        # 100 words for Grade 3 - animals, nature, common adjectives
        "elephant": "a very large animal with a trunk",
        "chocolate": "a sweet brown food",
        "teacher": "a person who helps students learn",
        "garden": "a place with plants and flowers",
        "yellow": "a bright color",
        "happy": "feeling good",
        "angry": "feeling mad",
        "tiger": "a big wild cat",
        "lion": "the king of animals",
        "zebra": "an animal with black and white stripes",
        "monkey": "a playful animal",
        "camel": "an animal that lives in deserts",
        "horse": "an animal for riding",
        "donkey": "an animal for carrying loads",
        "goat": "a farm animal",
        "sheep": "an animal with wool",
        "duck": "a water bird",
        "frog": "an animal that jumps",
        "snake": "a long animal without legs",
        "bear": "a large wild animal",
        "wolf": "a wild dog",
        "fox": "a clever animal",
        "deer": "an animal with antlers",
        "mouse": "a small animal",
        "rabbit": "a small animal that jumps",
        "parrot": "a bird that talks",
        "crow": "a black bird",
        "peacock": "a bird with colorful feathers",
        "eagle": "a strong bird",
        "kite": "a toy that flies",
        "boat": "used in water",
        "train": "vehicle on tracks",
        "truck": "a heavy vehicle",
        "market": "a place to buy and sell",
        "village": "a small town",
        "city": "a large town",
        "bridge": "a structure over water",
        "river": "flowing water",
        "mountain": "a very high land",
        "forest": "a place full of trees",
        "desert": "a dry sandy place",
        "rainbow": "colors seen after rain",
        "storm": "strong rain with wind",
        "earth": "the planet we live on",
        "world": "our planet",
        "family": "parents and children",
        "father": "male parent",
        "mother": "female parent",
        "brother": "male sibling",
        "sister": "female sibling",
        "friend": "a person you like",
        "child": "a young person",
        "people": "many persons",
        "group": "a set of people",
        "team": "people working together",
        "playground": "place to play",
        "school": "place to learn",
        "class": "group of students",
        "lesson": "part of study",
        "subject": "area of study",
        "math": "study of numbers",
        "science": "study of nature",
        "english": "a subject and language",
        "story": "a tale",
        "letter": "a character or message",
        "word": "a unit of language",
        "sentence": "a group of words",
        "book": "collection of pages",
        "page": "a sheet in a book",
        "library": "place with books",
        "pencil": "used for writing",
        "pen": "used for writing",
        "chalk": "used on board",
        "board": "used for writing",
        "desk": "table for students",
        "chair": "seat",
        "bag": "used to carry things",
        "box": "container",
        "clock": "shows time",
        "watch": "timepiece",
        "radio": "device for sound",
        "TV": "device for video",
        "computer": "machine for work",
        "phone": "device to talk",
        "lamp": "gives light",
        "fan": "cools air",
        "AC": "air cooler",
        "heater": "makes things warm",
        "oven": "for baking",
        "fridge": "keeps food cold",
        "sofa": "furniture for sitting",
        "table": "flat furniture",
        "bed": "furniture for sleeping",
    },

    4: {
        # 100 words for Grade 4 - longer words, concepts, geography, science
        "beautiful": "very pleasing to see",
        "mountain": "a very high landform",
        "language": "a way of speaking or writing",
        "computer": "an electronic machine for processing data",
        "science": "study of nature and experiments",
        "electric": "working with power",
        "energy": "power to do work",
        "motion": "movement",
        "gravity": "force that pulls things to Earth",
        "planet": "a body that orbits the sun",
        "galaxy": "a system of stars",
        "universe": "all space and matter",
        "school": "place to study",
        "teacher": "person who teaches",
        "student": "person who learns",
        "library": "place of books",
        "dictionary": "book of words",
        "history": "study of past",
        "geography": "study of Earth",
        "biology": "study of living things",
        "chemistry": "study of matter",
        "physics": "study of energy",
        "experiment": "a test in science",
        "microscope": "tool to see small things",
        "telescope": "tool to see far things",
        "engine": "machine that gives power",
        "bridge": "a structure over water",
        "tunnel": "a passage underground",
        "ocean": "a large body of salt water",
        "continent": "large land mass",
        "country": "land with people",
        "city": "a large town",
        "village": "a small town",
        "river": "water flow",
        "desert": "dry land",
        "forest": "land with trees",
        "climate": "weather over time",
        "weather": "conditions outside",
        "season": "time of year",
        "spring": "season of flowers",
        "summer": "hot season",
        "autumn": "fall season",
        "winter": "cold season",
        "machine": "device to do work",
        "engineer": "person who designs machines",
        "doctor": "person who treats sick people",
        "nurse": "helper in hospital",
        "hospital": "place for treatment",
        "medicine": "used to cure",
        "disease": "illness",
        "health": "condition of body",
        "exercise": "activity for health",
        "sports": "games for fitness",
        "football": "game with a ball",
        "cricket": "bat and ball game",
        "hockey": "stick and ball game",
        "tennis": "ball game with racket",
        "music": "sound with rhythm",
        "dance": "move with music",
        "drama": "acting on stage",
        "poem": "piece of writing",
        "novel": "long story",
        "author": "person who writes",
        "actor": "person who acts",
        "singer": "person who sings",
        "artist": "person who makes art",
        "painter": "person who paints",
        "sculptor": "person who makes statues",
        "king": "male ruler",
        "queen": "female ruler",
        "president": "head of state",
        "prime minister": "head of government",
        "police": "force that maintains law",
        "soldier": "person in army",
        "army": "group of soldiers",
        "navy": "sea force",
        "airforce": "air force",
        "law": "rules of country",
        "court": "place of justice",
        "judge": "person in court",
        "lawyer": "person who defends",
        "citizen": "member of country",
        "society": "group of people",
        "family": "group of relatives",
        "parents": "mother and father",
        "brother": "male sibling",
        "sister": "female sibling",
        "friend": "close person",
        "neighbor": "person living nearby",
        "guest": "visitor",
        "host": "person who receives",
    },

 5: {
        "achievement": "Something that has been done successfully, especially through effort.",
        "adaptation": "The process of adjusting to new conditions.",
        "adventure": "An exciting or unusual experience.",
        "ambition": "A strong desire to achieve something.",
        "ancient": "Very old; from a long time ago.",
        "astronomy": "The scientific study of stars, planets, and space.",
        "atmosphere": "The layer of gases surrounding the Earth.",
        "balance": "An even distribution of weight.",
        "biology": "The study of living things.",
        "bravery": "Courageous behavior or character.",
        "calendar": "A chart showing the days, weeks, and months of a year.",
        "challenge": "Something difficult that requires effort to overcome.",
        "character": "The qualities that make a person different from others.",
        "civilization": "A society with cities, government, and culture.",
        "climate": "The typical weather in a place over a long time.",
        "compass": "A tool used for finding direction.",
        "competition": "A contest between individuals or groups.",
        "conclusion": "The end or final part of something.",
        "conservation": "Protecting and preserving natural resources.",
        "continent": "One of the large land masses on Earth.",
        "courage": "The ability to face fear or danger.",
        "creativity": "The ability to think of new and original ideas.",
        "curiosity": "A strong desire to learn or know something.",
        "decade": "A period of ten years.",
        "decision": "A choice made after thinking.",
        "democracy": "A system of government by the people.",
        "dependable": "Able to be trusted and relied upon.",
        "design": "A plan or drawing for something that will be made.",
        "determine": "To decide firmly on something.",
        "dictionary": "A book that lists words and their meanings.",
        "direction": "The way something moves or points.",
        "discovery": "Finding something new or unknown.",
        "distance": "The amount of space between two things.",
        "electricity": "A form of energy used for power and light.",
        "emotion": "A strong feeling such as joy or sadness.",
        "energy": "The power to do work or cause change.",
        "environment": "The natural world around us.",
        "equator": "An imaginary line around the middle of the Earth.",
        "evaporation": "The process of liquid turning into gas.",
        "example": "A model or case used to show something.",
        "experience": "Knowledge gained through events in life.",
        "experiment": "A scientific test to learn something new.",
        "exploration": "The act of traveling to learn about new places.",
        "expression": "The act of showing feelings or ideas.",
        "famous": "Well-known by many people.",
        "fiction": "Stories that are made up and not real.",
        "flexible": "Able to bend without breaking; adaptable.",
        "fraction": "A part of a whole, like ½ or ¾.",
        "freedom": "The power to act without restriction.",
        "friendship": "A relationship between people who care for each other.",
        "friction": "The resistance between two surfaces that touch.",
        "function": "The purpose or role of something.",
        "generation": "All the people born around the same time.",
        "geography": "The study of Earth’s land, water, and features.",
        "geometry": "The study of shapes, sizes, and space.",
        "government": "The group of people who make decisions for a country.",
        "grammar": "The rules of a language.",
        "gravity": "The force that pulls objects toward the Earth.",
        "habitat": "The natural home of an animal or plant.",
        "harmony": "Peaceful agreement; pleasant combination of sounds.",
        "history": "The study of past events.",
        "horizon": "The line where the sky seems to meet the land or sea.",
        "imagination": "The ability to create ideas in your mind.",
        "important": "Of great value or significance.",
        "improve": "To make something better.",
        "independence": "Freedom from being controlled by others.",
        "influence": "The power to affect how someone thinks or acts.",
        "information": "Facts or details about something.",
        "inspiration": "Something that motivates or encourages you.",
        "instrument": "A tool or device used for a purpose, like music or science.",
        "intelligent": "Smart and able to think quickly.",
        "invention": "Something new created by people.",
        "justice": "Fairness and lawfulness.",
        "knowledge": "Understanding gained through study or experience.",
        "language": "A system of words used to communicate.",
        "leadership": "The ability to guide or direct others.",
        "library": "A place where books are kept for reading or borrowing.",
        "literature": "Written works such as books and stories.",
        "machine": "A tool with moving parts used to perform work.",
        "magnify": "To make something look larger.",
        "material": "What something is made of.",
        "measurement": "The size or amount of something.",
        "meteorology": "The study of weather.",
        "method": "A way of doing something.",
        "mixture": "A combination of two or more things.",
        "moment": "A very short period of time.",
        "mountain": "A very tall, high hill.",
        "movement": "The act of moving.",
        "multiplication": "A math operation of repeated addition.",
        "mystery": "Something unknown or hard to explain.",
        "nation": "A large group of people united under one government.",
        "natural": "Found in nature and not made by people.",
        "necessary": "Something needed or required.",
        "observation": "Carefully watching or noticing something.",
        "opinion": "What someone thinks or believes.",
        "organization": "A group of people with a specific purpose.",
        "oxygen": "The gas we breathe to live.",
        "participate": "To take part in something.",
        "pattern": "A repeated design or sequence.",
        "planet": "A large body that orbits a star.",
        "poetry": "Writing that uses rhythm and expression.",
        "population": "The number of people in a place.",
        "positive": "Good or hopeful.",
        "precious": "Very valuable or special.",
        "predict": "To say what will happen in the future.",
        "preserve": "To keep something safe or unchanged."
    },
    6: {
        "abandon": "To leave something behind completely.",
        "absorb": "To take in or soak up.",
        "abundant": "More than enough; plentiful.",
        "accuracy": "The state of being correct or exact.",
        "acquire": "To get or gain something.",
        "advantage": "Something helpful or useful.",
        "agriculture": "Farming and raising animals for food.",
        "analysis": "A careful study of something.",
        "ancestors": "People in your family who lived long ago.",
        "appropriate": "Suitable or correct for a situation.",
        "approximate": "Close to the exact number or value.",
        "argument": "A disagreement with reasons given.",
        "artifact": "An object made by humans, usually from the past.",
        "attract": "To pull toward something.",
        "available": "Ready for use or to be had.",
        "average": "The middle value in a group of numbers.",
        "behavior": "The way a person or animal acts.",
        "beneficial": "Helpful or good for something.",
        "brief": "Short in time or length.",
        "calculate": "To work out a number or problem.",
        "capacity": "The maximum amount something can hold.",
        "cause": "Something that makes something else happen.",
        "circulate": "To move around freely.",
        "combine": "To bring together.",
        "compare": "To find similarities and differences.",
        "complex": "Having many parts; not simple.",
        "component": "A part of a larger whole.",
        "compose": "To write or create.",
        "concentration": "Focusing your mind on something.",
        "consequence": "A result of an action.",
        "constant": "Something that does not change.",
        "construct": "To build something.",
        "contrast": "To show differences.",
        "contribute": "To give or add to something.",
        "convince": "To persuade someone to believe something.",
        "correspond": "To match or be similar.",
        "create": "To make something new.",
        "culture": "The beliefs and traditions of a group.",
        "data": "Facts and information used for study.",
        "decade": "A period of ten years.",
        "declare": "To announce something clearly.",
        "demonstrate": "To show how something works.",
        "depend": "To rely on something or someone.",
        "describe": "To explain something in detail.",
        "design": "A plan or drawing for making something.",
        "develop": "To grow or change over time.",
        "device": "A tool or machine made for a purpose.",
        "diffuse": "To spread out widely.",
        "diligent": "Working hard with care.",
        "dimension": "A measurable size such as length or width.",
        "distribute": "To give out to many people.",
        "diversity": "Variety; having many different kinds.",
        "dominate": "To control or have power over.",
        "economy": "The system of money and trade in a country.",
        "efficient": "Working well without wasting time or energy.",
        "elaborate": "To explain in detail.",
        "element": "A basic part of something.",
        "emerge": "To come into view or existence.",
        "emphasize": "To give special importance to something.",
        "encounter": "To meet unexpectedly.",
        "energy": "The ability to do work.",
        "enormous": "Very large in size.",
        "equivalent": "Equal in value or meaning.",
        "evaluate": "To judge or determine the value of something.",
        "evidence": "Proof that something is true.",
        "evolution": "The slow change of living things over time.",
        "examine": "To look at closely.",
        "exclude": "To leave out or not include.",
        "expand": "To grow larger.",
        "experiment": "A test to discover something new.",
        "explain": "To make something clear or easy to understand.",
        "expression": "The way someone shows their thoughts or feelings.",
        "factor": "One of the causes of something.",
        "feature": "An important part of something.",
        "fiction": "A made-up story.",
        "focus": "To concentrate on something.",
        "formal": "Done according to rules or tradition.",
        "frequent": "Happening often.",
        "function": "The purpose of something.",
        "generation": "People born around the same time.",
        "global": "Worldwide.",
        "historical": "Connected to history.",
        "hypothesis": "A possible explanation to test.",
        "identify": "To recognize or name something.",
        "illustrate": "To explain with pictures or examples.",
        "impact": "A strong effect on something.",
        "import": "To bring goods from another country.",
        "incident": "An event, often unusual or important.",
        "indicate": "To point out or show.",
        "individual": "One person or thing.",
        "influence": "The power to change someone’s actions or thoughts.",
        "innovation": "A new idea or method.",
        "intense": "Very strong or extreme.",
        "internal": "Inside something.",
        "interpret": "To explain the meaning of something.",
        "introduce": "To present something new.",
        "investigate": "To look into carefully to find facts."
    },
    7: {
        "abbreviate": "To shorten a word or phrase.",
        "absolute": "Complete and total.",
        "abstract": "Not concrete; existing in thought or idea.",
        "accelerate": "To speed up.",
        "accessible": "Easy to reach or use.",
        "accomplish": "To succeed in doing something.",
        "accumulate": "To gather or collect over time.",
        "adaptable": "Able to change easily to fit conditions.",
        "adequate": "Enough or satisfactory.",
        "advocate": "A person who supports a cause or idea.",
        "aesthetic": "Concerned with beauty or appearance.",
        "ambiguous": "Not clear; having more than one meaning.",
        "analyze": "To study carefully by breaking into parts.",
        "anticipate": "To expect something to happen.",
        "appreciate": "To value or be thankful for something.",
        "arbitrary": "Based on personal choice, not reason.",
        "artificial": "Made by humans, not natural.",
        "assess": "To evaluate or judge something.",
        "assign": "To give a task or responsibility.",
        "assume": "To suppose something is true without proof.",
        "authentic": "Real and genuine.",
        "available": "Able to be used or obtained.",
        "barrier": "Something that blocks movement or progress.",
        "benevolent": "Kind and generous.",
        "calculate": "To find an answer using math.",
        "capable": "Able to do something.",
        "category": "A group of things that are alike.",
        "chronological": "Arranged in the order of time.",
        "clarify": "To make something easier to understand.",
        "coincide": "To happen at the same time.",
        "collapse": "To fall down suddenly.",
        "colleague": "A person you work with.",
        "combine": "To bring together.",
        "commitment": "A promise to do something.",
        "commodity": "A product that is bought or sold.",
        "communicate": "To share information.",
        "compare": "To examine similarities and differences.",
        "compatible": "Able to work well together.",
        "compensate": "To make up for loss or damage.",
        "comprehend": "To understand fully.",
        "concentrate": "To focus your attention on something.",
        "concept": "An idea or thought.",
        "conclude": "To decide after thinking carefully.",
        "confer": "To discuss and exchange ideas.",
        "conflict": "A serious disagreement or fight.",
        "conform": "To follow rules or standards.",
        "consequence": "The result of an action.",
        "considerable": "Large or important.",
        "consistent": "Acting the same way over time.",
        "constant": "Happening all the time.",
        "construct": "To build something.",
        "consume": "To use up.",
        "contemporary": "Living or happening at the same time.",
        "context": "The situation or background of something.",
        "contradict": "To say the opposite of something.",
        "contribute": "To give something for a purpose.",
        "convey": "To communicate or carry.",
        "cooperate": "To work together for a purpose.",
        "correspond": "To match or be similar.",
        "credible": "Able to be believed or trusted.",
        "criteria": "Standards used to judge something.",
        "crucial": "Very important or necessary.",
        "cumulative": "Increasing as more is added.",
        "debate": "A formal discussion with opposing arguments.",
        "decipher": "To figure out the meaning of something.",
        "dedicate": "To give time or effort to a purpose.",
        "defend": "To protect from harm.",
        "define": "To explain the meaning of a word.",
        "demonstrate": "To show clearly with examples.",
        "derive": "To get something from a source.",
        "determine": "To decide firmly.",
        "develop": "To grow or improve over time.",
        "differentiate": "To recognize differences.",
        "diminish": "To make smaller or weaker.",
        "discriminate": "To treat unfairly based on differences.",
        "disperse": "To spread out in different directions.",
        "distinct": "Clearly different from others.",
        "distinguish": "To recognize the difference between things.",
        "diverse": "Varied and different.",
        "domestic": "Relating to the home or country.",
        "dominant": "Most powerful or important.",
        "economical": "Not wasteful; saving money or resources.",
        "eliminate": "To remove completely.",
        "emphasize": "To give importance to something.",
        "empirical": "Based on observation or experience.",
        "encounter": "To meet unexpectedly.",
        "enhance": "To improve or make better.",
        "enormous": "Extremely large.",
        "establish": "To set up or create.",
        "evaluate": "To judge the value of something.",
        "evidence": "Information that shows something is true.",
        "evolve": "To develop gradually.",
        "exceed": "To go beyond a limit.",
        "exclude": "To keep out or leave out.",
        "expand": "To increase in size.",
        "expertise": "Special knowledge or skill.",
        "expose": "To reveal something hidden.",
        "extract": "To remove something from a source.",
        "factor": "Something that influences a result.",
        "feasible": "Possible and practical to do."
    }
}

